### ISSUE TITLE
[BUG] An unexpected error occurred while trying to get the player uuid with the/auth uuid ID.

### ISSUE THREAD

**Issue by vocaloidkiss** [NikitaCartes/EasyAuth#105]
**Versions**
* EasyAuth 3.0.19
* Fabric API 0.87.0

**Describe the bug**
An unexpected error occurred while trying to get the player uuid with the/auth uuid ID.

The content is as follows
Format specifier %s

**Comment by vocaloidkiss** [comment]
another bug 
/remove uuid →crash

**Comment by NikitaCartes** [comment]
Can you send log please?

**Comment by vocaloidkiss** [comment]
[crash-2023-09-20_21.35.46-server.txt](https://github.com/NikitaCartes/EasyAuth/files/12677364/crash-2023-09-20_21.35.46-server.txt)

**Comment by vocaloidkiss** [comment]
[21:35:36] [Server thread/INFO]: rtyu[/127.0.0.1:50099] logged in with entity id 17045 at (1723.5, 71.0, -1516.5)
[21:35:36] [Server thread/INFO]: [Essential Commands] Loading PlayerData for player with uuid '32f23351-3db8-3af1-9305-f51a8b1c7b84'.
[21:35:36] [Server thread/INFO]: rtyu joined the game
[21:35:36] [Server thread/INFO]: [Essential Commands] Loading PlayerProfile for player with uuid '32f23351-3db8-3af1-9305-f51a8b1c7b84'.
[21:35:36] [Server thread/INFO]: Async chunk loading for player rtyu completed
[21:35:45] [Server thread/INFO]: rtyu lost connection: §aYour account was successfully deleted!
[21:35:45] [Server thread/INFO]: rtyu left the game
[21:35:45] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot read field "lastLocation" because "cache" is null
	at net.minecraft.class_3222.hidePosition(class_3222.java:7394) ~[server-intermediary.jar:?]
	at xyz.nikitacartes.easyauth.event.AuthEventHandler.onPlayerLeave(AuthEventHandler.java:160) ~[%5B轻松登录%5D%20easyauth-mc1.20-3.0.19.jar:?]
	at net.minecraft.class_3324.handler$chg000$easyauth$onPlayerLeave(class_3324.java:3528) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14611(class_3324.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_10839(class_3244.java:1228) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10768(class_2535.java:450) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:185) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zhl000$carpet$modifiedRunLoop(MinecraftServer.java:14942) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:35:46] [Server thread/ERROR]: This crash report has been saved to: C:\1.20.1\.\crash-reports\crash-2023-09-20_21.35.46-server.txt

**Comment by NikitaCartes** [comment]
Fixed in 3.0.21

**Comment by vocaloidkiss** [comment]
3.0.21 published？

**Comment by NikitaCartes** [comment]
@vocaloidkiss pre-release of it. You can find it here:
https://github.com/NikitaCartes/EasyAuth/releases/tag/3.0.21

**Comment by Phoupraw** [comment]
Is it fixed in 1.20.1?

**Comment by NikitaCartes** [comment]
@Phoupraw 
It was fixed in 1.20.3+

**Comment by Phoupraw** [comment]
Will it be back ported to 1.20.1? Or can that 1.20.3 jar run on 1.20.1 minecraft?

**Comment by NikitaCartes** [comment]
It will be at some point. 
No it will not run
