### ISSUE TITLE
[BUG] Crash: Mixin apply for mod easyauth failed: Invalid descriptor 

### ISSUE THREAD

**Issue by fr1g** [NikitaCartes/EasyAuth#107]
**Versions**
* EasyAuth 3.0.19, 3.0.0-17
* Fabric API 0.85.0:1.20.1

**Describe the bug**
Server crash on initialization with the mod.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add mod into Mods directory with other mods existing (these are ones I thought maybe  incompatible.): [banner, icommon, fabricProxy, lithium]
2. start the server

**Expected behaviour**
Server launched properly with the mod enabled.

**Additional context**
here's the logs:
`````text
[23:20:48] [ForkJoinPool.commonPool-worker-1/INFO]: Loaded 34 translation keys
[23:20:49] [main/ERROR]: Mixin apply for mod easyauth failed easyauth.mixins.json:PlayerManagerMixin from mod easyauth -> net.minecraft.server.players.PlayerList: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on easyauth.mixins.json:PlayerManagerMixin from mod easyauth->@Inject::migrateOfflineStats(Lnet/minecraft/world/entity/player/Player;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/UUID;Lnet/minecraft/stats/ServerStatsCounter;Ljava/io/File;Ljava/io/File;)V! Expected (Lnet/minecraft/world/entity/player/Player;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Lnet/minecraft/world/entity/player/Player;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/UUID;Lnet/minecraft/stats/ServerStatsCounter;Ljava/io/File;Ljava/io/File;)V [INJECT Applicator Phase -> easyauth.mixins.json:PlayerManagerMixin from mod easyauth -> Apply Injections ->  -> Inject -> easyauth.mixins.json:PlayerManagerMixin from mod easyauth->@Inject::migrateOfflineStats(Lnet/minecraft/world/entity/player/Player;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/UUID;Lnet/minecraft/stats/ServerStatsCounter;Ljava/io/File;Ljava/io/File;)V]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on easyauth.mixins.json:PlayerManagerMixin from mod easyauth->@Inject::migrateOfflineStats(Lnet/minecraft/world/entity/player/Player;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/UUID;Lnet/minecraft/stats/ServerStatsCounter;Ljava/io/File;Ljava/io/File;)V! Expected (Lnet/minecraft/world/entity/player/Player;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Lnet/minecraft/world/entity/player/Player;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/UUID;Lnet/minecraft/stats/ServerStatsCounter;Ljava/io/File;Ljava/io/File;)V [INJECT Applicator Phase -> easyauth.mixins.json:PlayerManagerMixin from mod easyauth -> Apply Injections ->  -> Inject -> easyauth.mixins.json:PlayerManagerMixin from mod easyauth->@Inject::migrateOfflineStats(Lnet/minecraft/world/entity/player/Player;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/UUID;Lnet/minecraft/stats/ServerStatsCounter;Ljava/io/File;Ljava/io/File;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:567) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.server.Main.lambda$main$3(Main.java:225) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.spin(MinecraftServer.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:224) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-mc.jar:0.11.2]
[23:20:49] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Mixin transformation of net.minecraft.server.players.PlayerList failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.server.Main.lambda$main$3(Main.java:225) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.spin(MinecraftServer.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:224) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-mc.jar:0.11.2]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	... 12 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [easyauth.mixins.json:PlayerManagerMixin from mod easyauth] from phase [DEFAULT] in config [easyauth.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	... 12 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on easyauth.mixins.json:PlayerManagerMixin from mod easyauth->@Inject::migrateOfflineStats(Lnet/minecraft/world/entity/player/Player;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/UUID;Lnet/minecraft/stats/ServerStatsCounter;Ljava/io/File;Ljava/io/File;)V! Expected (Lnet/minecraft/world/entity/player/Player;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V but found (Lnet/minecraft/world/entity/player/Player;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/UUID;Lnet/minecraft/stats/ServerStatsCounter;Ljava/io/File;Ljava/io/File;)V [INJECT Applicator Phase -> easyauth.mixins.json:PlayerManagerMixin from mod easyauth -> Apply Injections ->  -> Inject -> easyauth.mixins.json:PlayerManagerMixin from mod easyauth->@Inject::migrateOfflineStats(Lnet/minecraft/world/entity/player/Player;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/UUID;Lnet/minecraft/stats/ServerStatsCounter;Ljava/io/File;Ljava/io/File;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:567) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	... 12 more

**Comment by NikitaCartes** [comment]
I cannot recreate your error on Minecraft 1.20.1 with either mod version 3.0.0-17 or 3.0.19. What version of Minecraft do you use?

**Comment by fr1g** [comment]
1.20.1, the server .jar was downloaded from https://fabricmc.net/use/server/
What can cause these exception? I’ve tried check the json mentioned, and I cannot find anything weird.
Let me take a list of my mods in my server.
Or is there a possibility that, some bukkit plugins messed up the server?


Ps: list of mods (which printed by server)
 [main/WARN]: Warnings were found!
 - Mod 'Textile Backup' (textile_backup) 3.1.2-1.20 recommends any version of modmenu, which is missing!
         - You should install any version of modmenu for the optimal experience.
[03:20:10] [main/INFO]: Loading 120 mods:
        - antixray 1.3.1
           \-- com_moandjiezana_toml_toml4j 0.7.2
        - architectury 9.1.12
        - banner 1.20.1-473
           |-- com_github_llamalad7_mixinextras 0.2.0-beta.9
           |-- com_github_wdog5_mixin-tools 1.0.1
           |-- com_mohistmc_i18n 0.3
           |-- com_mohistmc_json 0.2
           |-- net_fabricmc_mapping-io 0.3.0
           |-- net_minecrell_terminalconsoleappender 1.4.0
           |-- org_apache_logging_log4j_log4j-iostreams 2.20.0
           |-- org_jline_jline-terminal 3.21.0
           |-- org_jline_jline-terminal-jansi 3.21.0
           \-- org_yaml_snakeyaml 1.33
        - c2me 0.2.0+alpha.11.0
           |-- c2me-base 0.2.0+alpha.11.0
           |-- c2me-client-uncapvd 0.2.0+alpha.11.0
           |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.0
           |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.0
           |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.0
           |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.0
           |-- c2me-notickvd 0.2.0+alpha.11.0
           |-- c2me-opts-allocs 0.2.0+alpha.11.0
           |-- c2me-opts-chunk-access 0.2.0+alpha.11.0
           |-- c2me-opts-chunkio 0.2.0+alpha.11.0
           |-- c2me-opts-math 0.2.0+alpha.11.0
           |-- c2me-opts-scheduling 0.2.0+alpha.11.0
           |-- c2me-opts-worldgen-general 0.2.0+alpha.11.0
           |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.0
           |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.0
           |-- c2me-rewrites-chunkio 0.2.0+alpha.11.0
           |-- c2me-server-utils 0.2.0+alpha.11.0
           |-- c2me-threading-chunkio 0.2.0+alpha.11.0
           |-- c2me-threading-lighting 0.2.0+alpha.11.0
           |-- c2me-threading-worldgen 0.2.0+alpha.11.0
           |-- com_electronwill_night-config_core 3.6.5
           |-- com_electronwill_night-config_toml 3.6.5
           |-- com_ibm_async_asyncutil 0.1.0
           |-- net_objecthunter_exp4j 0.4.8
           \-- org_threadly_threadly 7.0
        - cloth-config 11.1.106
           \-- cloth-basic-math 0.6.1
        - fabric-api 0.85.0+1.20.1
           |-- fabric-api-base 0.4.29+b04edc7a77
           |-- fabric-api-lookup-api-v1 1.6.34+4d8536c977
           |-- fabric-biome-api-v1 13.0.10+b3afc78b77
           |-- fabric-block-api-v1 1.0.9+e022e5d177
           |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b77
           |-- fabric-client-tags-api-v1 1.1.0+97bb207577
           |-- fabric-command-api-v1 1.2.32+f71b366f77
           |-- fabric-command-api-v2 2.2.11+b3afc78b77
           |-- fabric-commands-v0 0.2.49+df3654b377
           |-- fabric-containers-v0 0.1.61+df3654b377
           |-- fabric-content-registries-v0 4.0.8+b3afc78b77
           |-- fabric-convention-tags-v1 1.5.3+b3afc78b77
           |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
           |-- fabric-data-generation-api-v1 12.1.12+b3afc78b77
           |-- fabric-dimensions-v1 2.1.51+b3afc78b77
           |-- fabric-entity-events-v1 1.5.21+b3afc78b77
           |-- fabric-events-interaction-v0 0.6.0+b3afc78b77
           |-- fabric-events-lifecycle-v0 0.2.61+df3654b377
           |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
           |-- fabric-item-api-v1 2.1.26+b3afc78b77
           |-- fabric-item-group-api-v1 4.0.8+40e50c4677
           |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
           |-- fabric-keybindings-v0 0.2.34+df3654b377
           |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b77
           |-- fabric-loot-api-v2 1.1.38+b3afc78b77
           |-- fabric-loot-tables-v1 1.1.42+9e7660c677
           |-- fabric-message-api-v1 5.1.6+b3afc78b77
           |-- fabric-mining-level-api-v1 2.1.48+b3afc78b77
           |-- fabric-models-v0 0.3.35+b3afc78b77
           |-- fabric-networking-api-v1 1.3.8+b3afc78b77
           |-- fabric-networking-v0 0.3.48+df3654b377
           |-- fabric-object-builder-api-v1 11.1.0+6beca84877
           |-- fabric-particles-v1 1.1.0+201a23a077
           |-- fabric-recipe-api-v1 1.0.18+b3afc78b77
           |-- fabric-registry-sync-v0 2.2.6+b3afc78b77
           |-- fabric-renderer-api-v1 3.1.0+c154966e77
           |-- fabric-renderer-indigo 1.4.0+c154966e77
           |-- fabric-renderer-registries-v1 3.2.44+df3654b377
           |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b77
           |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b77
           |-- fabric-rendering-v0 1.1.47+df3654b377
           |-- fabric-rendering-v1 3.0.6+b3afc78b77
           |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
           |-- fabric-resource-loader-v0 0.11.8+e3d6ed2577
           |-- fabric-screen-api-v1 2.0.6+b3afc78b77
           |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b77
           |-- fabric-sound-api-v1 1.0.12+b3afc78b77
           |-- fabric-transfer-api-v1 3.2.3+43a3fedd77
           \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b77
        - fabricloader 0.14.21
        - fabricproxy 1.4.10
        - java 17
        - lithium 0.11.2
        - luckperms 5.4.102
           \-- fabric-permissions-api-v0 0.2-SNAPSHOT
        - minecraft 1.20.1
        - spark 1.10.53
        - tabtps-fabric 1.3.18
           |-- adventure-platform-fabric 5.10.0-SNAPSHOT
           |    |-- net_kyori_adventure-api 4.14.0
           |    |-- net_kyori_adventure-key 4.14.0
           |    |-- net_kyori_adventure-platform-api 4.3.0
           |    |-- net_kyori_adventure-text-logger-slf4j 4.14.0
           |    |-- net_kyori_adventure-text-minimessage 4.14.0
           |    |-- net_kyori_adventure-text-serializer-ansi 4.14.0
           |    |-- net_kyori_adventure-text-serializer-gson 4.14.0
           |    |-- net_kyori_adventure-text-serializer-json 4.14.0
           |    |-- net_kyori_adventure-text-serializer-plain 4.14.0
           |    |-- net_kyori_ansi 1.0.1
           |    |-- net_kyori_examination-api 1.3.0
           |    \-- net_kyori_examination-string 1.3.0
           |-- cloud 1.8.3
           |    |-- cloud_commandframework_cloud-brigadier_ 1.8.3
           |    |-- cloud_commandframework_cloud-core_ 1.8.3
           |    |-- cloud_commandframework_cloud-services_ 1.8.3
           |    |-- fabric-permissions-api-v0 0.2-SNAPSHOT
           |    \-- io_leangen_geantyref_geantyref 1.3.13
           |-- cloud_commandframework_cloud-minecraft-extras 1.8.3
           |-- com_typesafe_config 1.4.2
           |-- net_kyori_adventure-serializer-configurate4 4.14.0
           |-- net_kyori_adventure-text-feature-pagination 4.0.0-SNAPSHOT
           |-- net_kyori_adventure-text-serializer-legacy 4.14.0
           |-- org_spongepowered_configurate-core 4.1.2
           \-- org_spongepowered_configurate-hocon 4.1.2
        - textile_backup 3.1.2-1.20
           |-- com_github_shevek_parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
           |-- org_apache_commons_commons-compress 1.22
           \-- org_tukaani_xz 1.9
        - worldedit 7.2.15+6463-5ca4dff
        - xaerominimap 23.8.2
        - xaeroworldmap 1.34.1

**Comment by NikitaCartes** [comment]
It's happening because of Banner. They tried to fix compatibility with EasyAuth, but not very successfully:
https://github.com/MohistMC/Banner/commit/b9b16681d95fdb6f52750b22df0846063d9548bb

I will give a look into that, but no promises.

**Comment by fr1g** [comment]
Glad to hear that the problem found. It’s way better than know nothing about the reason of the issue :)

**Comment by fr1g** [comment]
Got something to ask: What will happen if I use your mod with BungeeCord? Just turn off bc’s online-mode and turn on fabric’s. I remember bc won’t connect to a spigot server if it’s online-mod on while bc’s off.
Btw I’m also using fabric-proxy to work with bc, as the list I sent to you before.

**Comment by NikitaCartes** [comment]
I do not have big experience with BungeeCord, so I can't really help with that part. I hear that's working fine with EasyAuth.
