### ISSUE TITLE
[BUG] Crash after auth remove

### ISSUE THREAD

**Issue by Kirkezz** [NikitaCartes/EasyAuth#110]
**Versions**
* EasyAuth 0.87.0
* Fabric API 3.0.19

**Describe the bug**
It looks like after my admin entered /auth remove command on a player that was online, server has crashed. He was trying to disable addToForcedOffline due to the fact that one of our players bought a minecraft license (I'll remove him in config.json from forcedOfflinePlayers but I wonder if there is a more convinient way).

**Additional context**
from server/logs:
```
[14:19:52] [Server thread/INFO]: <MrTvorozhok> щас буду сбрасывать пароль
[14:20:06] [Server thread/INFO]: [Not Secure] <ShlepaneCC2> у тебя плащ появился
[14:21:14] [Server thread/INFO]: ShlepaneCC2 lost connection: §aYour account was successfully deleted!
[14:21:14] [Server thread/INFO]: ShlepaneCC2 left the game
[14:21:14] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot read field "lastLocation" because "cache" is null
	at net.minecraft.class_3222.hidePosition(class_3222.java:1894) ~[server-intermediary.jar:?]
	at xyz.nikitacartes.easyauth.event.AuthEventHandler.onPlayerLeave(AuthEventHandler.java:160) ~[easyauth-mc1.20-3.0.19.jar:?]
	at net.minecraft.class_3324.handler$zzh000$easyauth$onPlayerLeave(class_3324.java:1028) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14611(class_3324.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_10839(class_3244.java:1228) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10768(class_2535.java:450) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:185) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:21:14] [Server thread/ERROR]: This crash report has been saved to: /opt/minecraft/server/./crash-reports/crash-2023-11-01_14.21.14-server.txt
[14:21:14] [Server thread/INFO]: Stopping server
[14:21:14] [Server thread/INFO]: Saving players
[14:21:14] [Server thread/INFO]: MrTvorozhok lost connection: Server closed
[14:21:14] [Server thread/INFO]: MrTvorozhok left the game
[14:21:14] [Server thread/INFO]: Saving worlds
[14:21:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[14:21:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[14:21:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[14:21:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[14:21:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[14:21:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[14:21:14] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[14:21:14] [Server thread/INFO]: [EasyAuth]: Shutting down EasyAuth.
[14:21:14] [Server thread/INFO]: [EasyAuth]: Database connection closed successfully
[14:21:14] [Server thread/INFO]: Thread RCON Listener stopped
```
crash report:
```
---- Minecraft Crash Report ----
// My bad.

Time: 2023-11-01 14:21:14
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot read field "lastLocation" because "cache" is null
	at net.minecraft.class_3222.hidePosition(class_3222.java:1894)
	at xyz.nikitacartes.easyauth.event.AuthEventHandler.onPlayerLeave(AuthEventHandler.java:160)
	at net.minecraft.class_3324.handler$zzh000$easyauth$onPlayerLeave(class_3324.java:1028)
	at net.minecraft.class_3324.method_14611(class_3324.java)
	at net.minecraft.class_3244.method_10839(class_3244.java:1228)
	at net.minecraft.class_2535.method_10768(class_2535.java:450)
	at net.minecraft.class_3242.method_14357(class_3242.java:185)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.4.0-165-generic
	Java Version: 17.0.8.1, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 341445232 bytes (325 MiB) / 2537553920 bytes (2420 MiB) up to 3250585600 bytes (3100 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5950X 16-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: GD 5446
	Graphics card #0 vendor: Cirrus Logic (0x1013)
	Graphics card #0 VRAM (MB): 32.00
	Graphics card #0 deviceId: 0x00b8
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 2983.96
	Virtual memory used (MB): 3260.25
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 1.76
	JVM Flags: 2 total; -Xms128M -Xmx3100M
	Fabric Mods: 
		audioplayer: AudioPlayer 1.20.1-1.7.1
		blackwolflibrary: Blackwolf Library 1.20.1-1.0.4-[FABRIC]
		chunky: Chunky 1.3.92
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		easyauth: Easy Authentication Mod 3.0.19
			at_favre_lib_bcrypt: bcrypt 0.9.0
			at_favre_lib_bytes: bytes 1.5.0
			com_mysql_mysql-connector-j: mysql-connector-j 8.0.33
			de_mkammerer_argon2-jvm: argon2-jvm 2.11
			de_mkammerer_argon2-jvm-nolibs: argon2-jvm-nolibs 2.11
			net_java_dev_jna_jna: jna 5.12.1
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_mongodb_bson: bson 4.7.2
			org_mongodb_mongodb-driver-core: mongodb-driver-core 4.7.2
			org_mongodb_mongodb-driver-sync: mongodb-driver-sync 4.7.2
			placeholder-api: Placeholder API 2.1.1+1.20
			server_translations_api: Server Translations API 2.0.0+1.20
				packet_tweaker: Packet Tweaker 0.4.0+1.19.4
		emotecraft: Emotecraft 2.2.7-b.build.50
			player-animator: Player Animator 1.0.2-rc1+1.20
		fabric-api: Fabric API 0.87.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.22
		java: OpenJDK 64-Bit Server VM 17
		ledger: Ledger 1.2.8
		lithium: Lithium 0.11.2
		minecraft: Minecraft 1.20.1
		modid: Example mod 1.0.0
		moredecorativeblocks: More Decorative Blocks 1.20.1-1.0.4-[FABRIC]
		omnihopper: Omni-Hopper 2.2.1+1.20
			cicada: CICADA 0.4.0
				com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
			cooldown-coordinator: Cooldown Coordinator 0.6.2
		plushies: Plushie Mod 1.2.1
		redstonebits: Redstone Bits 1.10.2
		universal-graves: Universal Graves 3.0.0-pre.1+1.20.1
			common-protection-api: Common Protection API 1.0.0
			polymer-core: Polymer (Core) 0.5.7+1.20.1
				polymer-networking: Polymer (Networking) 0.5.7+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.7+1.20.1
			polymer-resource-pack: Polymer (Resource Pack) 0.5.7+1.20.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.5.7+1.20.1
				polymer-common: Polymer (Common) 0.5.7+1.20.1
			predicate-api: Predicate API 0.1.2+1.20
			sgui: sgui 1.2.2+1.20
		voicechat: Simple Voice Chat 1.20.1-2.4.24
		voicechat-discord: Simple Voice Chat Discord Bridge 2.1.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
	Server Running: true
	Player Count: 2 / 20; [class_3222['MrTvorozhok'/242071, l='ServerLevel[world]', x=38.10, y=69.00, z=67.94], class_3222['ShlepaneCC2'/246905, l='ServerLevel[world]', x=37.62, y=70.00, z=62.33]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Kirkezz** [comment]
UPD: this (Cannot read field "lastLocation" because "cache" is null) looks like a duplicate of https://github.com/NikitaCartes/EasyAuth/issues/105
