### ISSUE TITLE
[BUG] EasyAuth does not support MySQL 8

### ISSUE THREAD

**Issue by TheLegendarySpark** [NikitaCartes/EasyAuth#112]
**Versions**
* EasyAuth 1.20-3.0.19
* Fabric API 0.14.24

**Describe the bug**
I tried to connect EasyAuth to MySQL 8 but an error occurs:
```
Caused by: com.mysql.cj.exceptions.UnableToConnectException: Public Key Retrieval is not allowed
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:86)
        at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:130)
        ... 21 more
```

**To Reproduce**
1. Fill in the basic MySQL details in the config yml file
2. Run a MySQL 8 database with the credentials you used above
3. Do `/auth reload`

**Expected behavior**
No errors

**Additional context**
None at the moment

**Comment by NikitaCartes** [comment]
Did you try `allowPublicKeyRetrieval=true`?
https://stackoverflow.com/questions/50379839/connection-java-mysql-public-key-retrieval-is-not-allowed

**Comment by NikitaCartes** [comment]
Feel free to reopen
