### ISSUE TITLE
[BUG] Server Can't Start When Update Plugin Version

### ISSUE THREAD

**Issue by MyBlueHorizon** [NikitaCartes/EasyAuth#130]
**Versions**
* EasyAuth 3.0.22
* Fabric API 0.96.4

**Describe the bug**
Server can't start when update plugin version.

**To Reproduce**
1. Download the latest version from Github.
2. Start server.
4. See error.

**Expected behavior**
Server can start.

**Additional context**
```
[main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'easyauth'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.6.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.6.jar:?]
Caused by: java.lang.RuntimeException: [EasyAuth] Failed to load config file
	at xyz.nikitacartes.easyauth.config.ConfigTemplate.loadConfig(ConfigTemplate.java:42) ~[easyauth-mc1.20.4-3.0.22-SNAPSHOT.jar:?]
	at xyz.nikitacartes.easyauth.config.TechnicalConfigV1.load(TechnicalConfigV1.java:29) ~[easyauth-mc1.20.4-3.0.22-SNAPSHOT.jar:?]
	at xyz.nikitacartes.easyauth.EasyAuth.loadConfigs(EasyAuth.java:179) ~[easyauth-mc1.20.4-3.0.22-SNAPSHOT.jar:?]
	at xyz.nikitacartes.easyauth.EasyAuth.onInitialize(EasyAuth.java:86) ~[easyauth-mc1.20.4-3.0.22-SNAPSHOT.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
	... 6 more
Caused by: org.spongepowered.configurate.loader.ParsingException: []: Unknown error occurred while loading
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:165) ~[org_spongepowered_configurate-core-4.1.2-9950dcf1ea1d8c3b.jar:?]
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:63) ~[org_spongepowered_configurate-core-4.1.2-9950dcf1ea1d8c3b.jar:?]
	at org.spongepowered.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:56) ~[org_spongepowered_configurate-core-4.1.2-9950dcf1ea1d8c3b.jar:?]
	at xyz.nikitacartes.easyauth.config.ConfigTemplate.loadConfig(ConfigTemplate.java:40) ~[easyauth-mc1.20.4-3.0.22-SNAPSHOT.jar:?]
	at xyz.nikitacartes.easyauth.config.TechnicalConfigV1.load(TechnicalConfigV1.java:29) ~[easyauth-mc1.20.4-3.0.22-SNAPSHOT.jar:?]
	at xyz.nikitacartes.easyauth.EasyAuth.loadConfigs(EasyAuth.java:179) ~[easyauth-mc1.20.4-3.0.22-SNAPSHOT.jar:?]
	at xyz.nikitacartes.easyauth.EasyAuth.onInitialize(EasyAuth.java:86) ~[easyauth-mc1.20.4-3.0.22-SNAPSHOT.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
	... 6 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 3, Size: 2
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:756) ~[?:?]
	at java.util.ArrayList.add(ArrayList.java:481) ~[?:?]
	at org.spongepowered.configurate.ListConfigValue.putChildInternal(ListConfigValue.java:178) ~[org_spongepowered_configurate-core-4.1.2-9950dcf1ea1d8c3b.jar:?]
	at org.spongepowered.configurate.ListConfigValue.putChildInternal(ListConfigValue.java:149) ~[org_spongepowered_configurate-core-4.1.2-9950dcf1ea1d8c3b.jar:?]
	at org.spongepowered.configurate.ListConfigValue.putChild(ListConfigValue.java:128) ~[org_spongepowered_configurate-core-4.1.2-9950dcf1ea1d8c3b.jar:?]
	at org.spongepowered.configurate.AbstractConfigurationNode.attachChild(AbstractConfigurationNode.java:615) ~[org_spongepowered_configurate-core-4.1.2-9950dcf1ea1d8c3b.jar:?]
	at org.spongepowered.configurate.AbstractConfigurationNode.attachChild(AbstractConfigurationNode.java:555) ~[org_spongepowered_configurate-core-4.1.2-9950dcf1ea1d8c3b.jar:?]
	at org.spongepowered.configurate.AbstractConfigurationNode.attachIfNecessary(AbstractConfigurationNode.java:545) ~[org_spongepowered_configurate-core-4.1.2-9950dcf1ea1d8c3b.jar:?]
	at org.spongepowered.configurate.AbstractConfigurationNode.insertNewValue(AbstractConfigurationNode.java:239) ~[org_spongepowered_configurate-core-4.1.2-9950dcf1ea1d8c3b.jar:?]
	at org.spongepowered.configurate.AbstractConfigurationNode.raw(AbstractConfigurationNode.java:340) ~[org_spongepowered_configurate-core-4.1.2-9950dcf1ea1d8c3b.jar:?]
	at org.spongepowered.configurate.hocon.HoconConfigurationLoader.readConfigValue(HoconConfigurationLoader.java:221) ~[org_spongepowered_configurate-hocon-4.1.2-d1e6f200f2124a26.jar:?]
	at org.spongepowered.configurate.hocon.HoconConfigurationLoader.readConfigValue(HoconConfigurationLoader.java:214) ~[org_spongepowered_configurate-hocon-4.1.2-d1e6f200f2124a26.jar:?]
	at org.spongepowered.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:179) ~[org_spongepowered_configurate-hocon-4.1.2-d1e6f200f2124a26.jar:?]
	at org.spongepowered.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:61) ~[org_spongepowered_configurate-hocon-4.1.2-d1e6f200f2124a26.jar:?]
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:155) ~[org_spongepowered_configurate-core-4.1.2-9950dcf1ea1d8c3b.jar:?]
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:63) ~[org_spongepowered_configurate-core-4.1.2-9950dcf1ea1d8c3b.jar:?]
	at org.spongepowered.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:56) ~[org_spongepowered_configurate-core-4.1.2-9950dcf1ea1d8c3b.jar:?]
	at xyz.nikitacartes.easyauth.config.ConfigTemplate.loadConfig(ConfigTemplate.java:40) ~[easyauth-mc1.20.4-3.0.22-SNAPSHOT.jar:?]
	at xyz.nikitacartes.easyauth.config.TechnicalConfigV1.load(TechnicalConfigV1.java:29) ~[easyauth-mc1.20.4-3.0.22-SNAPSHOT.jar:?]
	at xyz.nikitacartes.easyauth.EasyAuth.loadConfigs(EasyAuth.java:179) ~[easyauth-mc1.20.4-3.0.22-SNAPSHOT.jar:?]
	at xyz.nikitacartes.easyauth.EasyAuth.onInitialize(EasyAuth.java:86) ~[easyauth-mc1.20.4-3.0.22-SNAPSHOT.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
	... 6 more
```

**Comment by NikitaCartes** [comment]
Can you please send `config/EasyAuth/technical.conf` or/and `mods/EasyAuth/config.json` here or in Discord dm?

**Comment by MyBlueHorizon** [comment]
I think "null" is the problem.
(I don't know why "null" will appear)
technical.conf
\# List of players that was confirmed as online.
confirmed-online-players: [A,
  null,
  B]
config.json
"verifiedOnlinePlayer": [
      "A",
      null,
      "B"
    ],

**Comment by NikitaCartes** [comment]
Yes, null is the problem.
You can delete null, and mod should work after that.

I will fix config migration to fix it, thanks
