### ISSUE TITLE
[BUG] Needs to be updated for 1.21.3

### ISSUE THREAD

**Issue by EnKrypt** [NikitaCartes/EasyAuth#169]
**Versions**
* EasyAuth 3.0.25
* Fabric API 0.106.1+1,21.3

**Describe the bug**
When starting a 1.21.3 java edition server, the startup fails with the following error stack:
```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'easyauth' at 'xyz.nikitacartes.easyauth.EasyAuth'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.7.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.7.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.3-loader.0.16.7-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_1271
        at knot/xyz.nikitacartes.easyauth.EasyAuth.onInitialize(EasyAuth.java:117) ~[easyauth-mc1.21-3.0.25.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.7.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1271
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.7.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at knot/xyz.nikitacartes.easyauth.EasyAuth.onInitialize(EasyAuth.java:117) ~[easyauth-mc1.21-3.0.25.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.7.jar:?]
        ... 7 more
```

**To Reproduce**
1. Have a 1.21.3 java edition server with a compatible fabric loader and fabric api mod.
2. Put easyauth jar into the mods folder.
3. Start the server

**Expected behavior**
Server should successfully start with the mod working.

**Additional context**
NA

**Comment by NikitaCartes** [comment]
Fixed
