### ISSUE TITLE
[BUG]Invalid player data

### ISSUE THREAD

**Issue by Dreeam-qwq** [NikitaCartes/EasyAuth#25]
**Versions**
* Server 1.18.1
* EasyAuth 2.0.6
* Fabric API 0.44.0

**Describe the bug**
Players get kick when join server. The kick message shows that "Invalid player data" and see error on console.

**To Reproduce**
1. Launch offline mod server with easyauth and other mods.
2. Log in with offline account.
3. Get kick and see error in console.

**Expected behavior**
Player can join server and log in without error.

**Additional context**
The error when player join server

```
[15:37:48] [Server thread/INFO]: Dreeam[/127.0.0.1:12817] logged in with entity id 64 at (244.95024941280744, 78.62892901314035, 1388.5737279350697)
[15:37:48] [Server thread/INFO]: §eDreeam joined the game
[15:37:49] [Server thread/ERROR]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8401()" because "$$0" is null
	at net.minecraft.class_3222.method_14251(class_3222.java:1478) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.hidePosition(class_3222.java:3772) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.setAuthenticated(class_3222.java:3832) ~[server-intermediary.jar:?]
	at xyz.nikitacartes.easyauth.event.AuthEventHandler.onPlayerJoin(AuthEventHandler.java:98) ~[easyauth-mc1.18-2.0.6.jar:?]
	at net.minecraft.class_3324.handler$zob000$onPlayerConnect(class_3324.java:3460) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:281) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:117) [server-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$bap000$handlePlayerJoin(class_3248.java:1063) [server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:67) [server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:234) [server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:890) [server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:324) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zgn000$modifiedRunLoop(MinecraftServer.java:3856) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) [server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$6105/0x00000000bfb51fa0.run(Unknown Source) [server-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
[15:37:49] [Server thread/INFO]: Dreeam lost connection: Invalid player data
[15:37:49] [Server thread/INFO]: §eDreeam left the game
[15:37:49] [Server thread/WARN]: handleDisconnection() called twice
```

**Comment by NikitaCartes** [comment]
Check your `config.worldSpawn.dimension` setting or set spawn via [command](https://github.com/NikitaCartes/EasyAuth/wiki/Coordinate-Hiding)

**Comment by Dreeam-qwq** [comment]
> Check your `config.worldSpawn.dimension` setting or set spawn via [command](https://github.com/NikitaCartes/EasyAuth/wiki/Coordinate-Hiding)

Problem solved, thank you!

**Comment by hrustmonet3d** [comment]
How problem was solved?

**Comment by hrustmonet3d** [comment]
How was solved the problem?

**Comment by NikitaCartes** [comment]
@hrustmonet3d you need to set spawn with `\auth setSpawn`
