### ISSUE TITLE
[BUG] Server Text won't properly display. 1.18.2

### ISSUE THREAD

**Issue by Ozakinn** [NikitaCartes/EasyAuth#36]
**Versions**
* EasyAuth 2.2.2
* Fabric API 0.48.0+1.18.2

**Describe the bug**
The mod should display or send a message to a player to login or register. however, it send incorrect text format. as it was a placeholder thing. i dont know what it is. it was working fine using easyauth 2.1.0. Probably break in 1.18.2.

It seems that lang inside the config file doesnt work.

**To Reproduce**
1. add the mod to 1.18.2 server
2. join the server
3. See the white text message to login with incorrect format.

**Expected behavior**
should send a message saying **You are not authenticated! /login or /l to authenticate!**
![image_2022-03-22_221449](https://user-images.githubusercontent.com/21289418/159502004-a4545d77-6b80-4023-b15e-07772bf1d1f9.png)
![bug01](https://user-images.githubusercontent.com/21289418/159502021-c06d208c-3d86-4f29-8922-323ba5f357c9.png)

**Comment by NikitaCartes** [comment]
While I inspect this you can mitigate issue you can set `enableServerSideTranslation ` to false

**Comment by Ozakinn** [comment]
Thanks. Its working now. back to normal.
I didnt modify anything(specifically that exprimental) that before maybe the new patch set it to true??

**Comment by NikitaCartes** [comment]
`enableServerSideTranslation` exists for rare cases when translations doesn't work automatically. 
It always was set to `true` in code but before 2.0.6 it wasn't a separate option

**Comment by Glucy-2** [comment]
I cannot load the mod on 1.18.2:
````
[Server] [14:57:40] [main/ERROR]: Mixin apply for mod easyauth failed easyauth.mixins.json:WorldSaveHandlerMixin -> net.minecraft.class_29: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field field_149 was not located in the target class net.minecraft.class_29. Using refmap easyauth-mc1.18-refmap.json
[Server] org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_149 was not located in the target class net.minecraft.class_29. Using refmap easyauth-mc1.18-refmap.json
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]     at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
[Server]        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[Server]        at net.minecraft.class_32$class_5143.method_27427(class_32.java:339) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:302) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3176.<init>(class_3176.java:84) ~[server-intermediary.jar:?]
[Server]     at net.minecraft.server.Main.method_29734(Main.java:213) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:280) [server-intermediary.jar:?]
[Server]        at net.minecraft.server.Main.main(Main.java:212) [server-intermediary.jar:?]
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[Server]        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[Server]        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
[Server]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[Server]        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[Server]        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
[Server]        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]
[Server]        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:64) [fabric-server-mc.1.18.2-loader.0.13.3-launcher.0.10.2.jar:0.10.2]
[Server] [14:57:40] [main/ERROR]: Failed to start the minecraft server
[Server] java.lang.RuntimeException: Mixin transformation of net.minecraft.class_29 failed
[Server]     at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
[Server]        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[Server]        at net.minecraft.class_32$class_5143.method_27427(class_32.java:339) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:302) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3176.<init>(class_3176.java:84) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.Main.method_29734(Main.java:213) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:280) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.Main.main(Main.java:212) [server-intermediary.jar:?]
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[Server]        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[Server]        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
[Server]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[Server]        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[Server]     at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
[Server]        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]
[Server]        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:64) [fabric-server-mc.1.18.2-loader.0.13.3-launcher.0.10.2.jar:0.10.2]
[Server] Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[Server]        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]     at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
[Server]        ... 22 more
[Server] Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [easyauth.mixins.json:WorldSaveHandlerMixin] from phase [DEFAULT] in config [easyauth.mixins.json] from mod [easyauth] FAILED during APPLY
[Server]        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
[Server]        ... 22 more
[Server] Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_149 was not located in the target class net.minecraft.class_29. Using refmap easyauth-mc1.18-refmap.json
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
[Server]        ... 22 more
```

**Comment by NikitaCartes** [comment]
@Glucy-2 
it's seems you are using 1.18 version which are incompatible with 1.18.2

**Comment by Glucy-2** [comment]
OK, thanks
I've found the 1.18.2 ver
