### ISSUE TITLE
Crash on 1.18.2

### ISSUE THREAD

**Issue by molaeiali** [NikitaCartes/EasyAuth#38]
**Versions**
* EasyAuth 1.18-2.1.0
* Fabric API 0.48.0+1.18.2

**Describe the bug**
I'm getting this error when starting the server

```
0|mc  | java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'easyauth'!
0|mc  | 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
0|mc  | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
0|mc  | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
0|mc  | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
0|mc  | 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
0|mc  | 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
0|mc  | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
0|mc  | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
0|mc  | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
0|mc  | 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
0|mc  | 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]
0|mc  | Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5350 failed
0|mc  | 	at xyz.nikitacartes.easyauth.EasyAuth.onInitialize(EasyAuth.java:125) ~[easyauth-mc1.18-2.1.0.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	... 15 more
0|mc  | Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5350 failed
0|mc  | 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
0|mc  | 	at xyz.nikitacartes.easyauth.EasyAuth.onInitialize(EasyAuth.java:125) ~[easyauth-mc1.18-2.1.0.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	... 15 more
0|mc  | Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
0|mc  | 	at xyz.nikitacartes.easyauth.EasyAuth.onInitialize(EasyAuth.java:125) ~[easyauth-mc1.18-2.1.0.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	... 15 more
0|mc  | Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [server_translations_api.mixin.json:ServerResourceManagerMixin] from phase [DEFAULT] in config [server_translations_api.mixin.json] from mod [server_translations_api] FAILED during APPLY
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
0|mc  | 	at xyz.nikitacartes.easyauth.EasyAuth.onInitialize(EasyAuth.java:125) ~[easyauth-mc1.18-2.1.0.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	... 15 more
0|mc  | Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_25335 was not located in the target class net.minecraft.class_5350. Using refmap server-translations-api-refmap.json
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
0|mc  | 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
0|mc  | 	at xyz.nikitacartes.easyauth.EasyAuth.onInitialize(EasyAuth.java:125) ~[easyauth-mc1.18-2.1.0.jar:?]
0|mc  | 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
0|mc  | 	... 15 more
```

**Comment by NikitaCartes** [comment]
Download version for 1.18.2 (on CurseForge or Modrinth)

**Comment by molaeiali** [comment]
> Download version for 1.18.2 (on CurseForge or Modrinth)

Sorry, for being late to reply, In the CurseForge, there is a version marked as 1.18.x and it's on top

I think that has confused me to download the wrong version, is the .x at the end necessary?

**Comment by Ivan-Khar** [comment]
You need to download 1.18.2 version of the mod, not 1.18.x

if you click on 1.18.x version you can see that this version is only for 1.18-1.18.1

**Comment by Ivan-Khar** [comment]
https://www.curseforge.com/minecraft/mc-mods/easyauth/files/3668308

**Comment by molaeiali** [comment]
> https://www.curseforge.com/minecraft/mc-mods/easyauth/files/3668308
> 

Yes I know, I downloaded it and it works

I say that 1.18.x is misleading, 1.18.x includes 1.18.1 1.18.2 .... 1.18.9 etc. Shouldn't be just 1.18 without .x ?

**Comment by NikitaCartes** [comment]
> Shouldn't be just 1.18 without .x

You are right. I renamed it to [1.18; 1.18.1]
