### ISSUE TITLE
[BUG] Crash when using mods that use Fake Player API (Create, ComputerCraft probably)

### ISSUE THREAD

**Issue by otomir23** [NikitaCartes/EasyAuth#46]
**Versions**
* EasyAuth 2.2.2
* Fabric API 0.53.4

**Describe the bug**
Server crashes during usage of Fake Plaer API on blocks.

**To Reproduce**
1. Install any mod that uses Fake Player API (Create, ComputerCraft, etc)
2. Do action that requires use of block interaction as a fake player (Deployer from Create, turtle from CC)
3. Server crashes

**Expected behavior**
Server doesn't crash lol

**Additional context**
Block interaction while player is not logged in is disabled.

Stacktrace:
```Description: Ticking block entity

java.lang.NullPointerException: Cannot read field "password" because "cache" is null
	at net.minecraft.class_3222.getAuthMessage(class_3222.java:3323)
	at xyz.nikitacartes.easyauth.event.AuthEventHandler.onUseBlock(AuthEventHandler.java:184)
	at xyz.nikitacartes.easyauth.EasyAuth.lambda$onInitialize$2(EasyAuth.java:121)
	at net.fabricmc.fabric.api.event.player.UseBlockCallback.lambda$static$0(UseBlockCallback.java:41)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerHandler.activateInner(DeployerHandler.java:269)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerHandler.activate(DeployerHandler.java:131)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.activate(DeployerTileEntity.java:318)
	at com.simibubi.create.content.contraptions.components.deployer.DeployerTileEntity.tick(DeployerTileEntity.java:226)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntityTicker.tick(SmartTileEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:368)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by NikitaCartes** [comment]
I didn't test it but it should work. I hope it work xD

It's would be very cool if you test [this build](https://github.com/NikitaCartes/EasyAuth/suites/6787281473/artifacts/260157322)

**Comment by booleancoercion** [comment]
Hey! We're running a Fabric server, and it looks like EasyAuth is still causing crashes when coupled with computercraft turtles. EasyAuth version 3.0.0-6 (latest for 1.18.2 at the time of writing) for minecraft 1.18.2, and fabric API 0.59.1. Here's the stack trace:

```
java.lang.NullPointerException: Cannot read field "password" because "cache" is null
	at net.minecraft.class_3222.getAuthMessage(class_3222.java:12820)
	at xyz.nikitacartes.easyauth.event.AuthEventHandler.onBreakBlock(AuthEventHandler.java:197)
	at xyz.nikitacartes.easyauth.EasyAuth.lambda$onInitialize$1(EasyAuth.java:136)
	at net.fabricmc.fabric.api.event.player.PlayerBlockBreakEvents.lambda$static$0(PlayerBlockBreakEvents.java:42)
	at dan200.computercraft.shared.turtle.upgrades.TurtleTool.dig(TurtleTool.java:229)
	at dan200.computercraft.shared.turtle.upgrades.TurtleTool.useTool(TurtleTool.java:110)
	at dan200.computercraft.shared.turtle.core.TurtleToolCommand.execute(TurtleToolCommand.java:39)
	at dan200.computercraft.shared.turtle.core.TurtleBrain.updateCommands(TurtleBrain.java:777)
	at dan200.computercraft.shared.turtle.core.TurtleBrain.update(TurtleBrain.java:130)
	at dan200.computercraft.shared.turtle.blocks.TileTurtle.serverTick(TileTurtle.java:201)
	at dan200.computercraft.shared.computer.blocks.BlockComputerBase.lambda$new$0(BlockComputerBase.java:44)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:475)
	at net.minecraft.class_3218.method_18765(class_3218.java:368)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
I should note we're also using Create and it *hasn't* caused crashes, so the fix above must've done something to prevent that.

**Comment by rdrpenguin04** [comment]
We've tried to fix this crash ourselves, but we can't pull the FakePlayerAPI jar; not sure how we go about fixing that.
