### ISSUE TITLE
I can't connect the database...

### ISSUE THREAD

**Issue by KoTeHok22** [NikitaCartes/EasyAuth#57]
Please help me connect the MySQL database

**Comment by NikitaCartes** [comment]
I can't help you without log or anything

**Comment by KoTeHok22** [comment]
Can you show an example of how to connect? Maybe I'm just typing incorrectly..

**Comment by NikitaCartes** [comment]
```"
databaseType": "mysql",
"MySQLHost": "<address of your DB>",
"MySQLUser": "<user of DB>",
"MySQLPassword": "<password for that user>,
"MySQLDatabase": "easyauth",
"MySQLTableName": "easyauth
```

**Comment by KoTeHok22** [comment]
When trying to restart the config, the server crashed... When you try to start it again, it freezes at startup..

[20:22:48] [main/INFO]: [EasyAuth] EasyAuth mod by samo_lego, NikitaCartes
[crash-2022-07-25_20.18.12-server.txt](https://github.com/NikitaCartes/EasyAuth/files/9184228/crash-2022-07-25_20.18.12-server.txt)
.

**Comment by KoTeHok22** [comment]
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.prepareStatement(String)" because "this.MySQLConnection" is null
        at xyz.nikitacartes.easyauth.storage.database.MySQL.isUserRegistered(MySQL.java:96) ~[easyauth-mc1.18.2-3.0.0-6.jar:?]
        at xyz.nikitacartes.easyauth.storage.database.MySQL.getUserData(MySQL.java:149) ~[easyauth-mc1.18.2-3.0.0-6.jar:?]
        at xyz.nikitacartes.easyauth.storage.PlayerCache.fromJson(PlayerCache.java:92) ~[easyauth-mc1.18.2-3.0.0-6.jar:?]
        at xyz.nikitacartes.easyauth.event.AuthEventHandler.onPlayerJoin(AuthEventHandler.java:95) ~[easyauth-mc1.18.2-3.0.0-6.jar:?]
        at net.minecraft.class_3324.handler$zeg000$onPlayerConnect(class_3324.java:1960) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:282) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_33800(class_3248.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:117) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.redirect$zib000$handlePlayerJoin(class_3248.java:1063) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_18785(class_3248.java:67) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:243) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:322) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by NikitaCartes** [comment]
Is there any errors before that? Can you give `latest.log`?
And I think in [Discord](https://discord.gg/UY4nhvUzaK) it would be easier.

**Comment by NikitaCartes** [comment]
For anyone who got any errors with DB in future: check if you can connect to DB with other apps (DB Manager, IDEA, other mods, etc)
