### ISSUE TITLE
Exception on startup in Docker [BUG]

### ISSUE THREAD

**Issue by sdas-tech** [NikitaCartes/EasyAuth#6]
**Versions**
* EasyAuth easyauth-mc1.17.1-1.9.3.jar
* Fabric API fabric-api-0.37.1+1.17.jar

**Describe the bug**

Getting this exception on startup of the server:
```
mc_1  | [13:54:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/data/fabric-server-1.17.1.jar Service=Knot/Fabric Env=SERVER
mc_1  | [13:54:51] [main/INFO]: Compatibility level set to JAVA_16
mc_1  | [13:54:51] [main/INFO]: Loaded configuration file for Lithium: 80 options available, 0 override(s) found
mc_1  | [13:54:52] [main/WARN]: @Mixin target net/minecraft/class_3218$class_5526 is public in fabric-lifecycle-events-v1.mixins.json:ServerWorldEntityLoaderMixin and should be specified in value
mc_1  | [13:54:52] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
mc_1  | [13:54:52] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
mc_1  | [13:55:00] [main/INFO]: [EasyAuth] EasyAuth mod by samo_lego, NikitaCartes.
mc_1  | [13:55:00] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zzm000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
mc_1  | **[13:55:00] [main/FATAL]: Failed to start the minecraft server
mc_1  | java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'easyauth'!
mc_1  |         at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-1.17.1.jar:?]
mc_1  |         at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-server-1.17.1.jar:?]
mc_1  |         at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-1.17.1.jar:?]
mc_1  |         at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
mc_1  |         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
mc_1  |         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
mc_1  |         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
mc_1  |         at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
mc_1  |         at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-1.17.1.jar:?]
mc_1  |         at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-1.17.1.jar:?]
mc_1  |         at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-1.17.1.jar:?]
mc_1  |         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
mc_1  |         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
mc_1  |         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
mc_1  |         at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
mc_1  |         at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-1.17.1.jar:?]
mc_1  |         at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-1.17.1.jar:?]
mc_1  |         at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-1.17.1.jar:?]
mc_1  | Caused by: java.lang.IllegalArgumentException: Database directory './mods/EasyAuth/levelDBStore' does not exist and could not be created
mc_1  |         at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[fabric-server-1.17.1.jar:?]
mc_1  |         at org.iq80.leveldb.impl.DbImpl.<init>(DbImpl.java:163) ~[90026451-88ee-4ee5-a48c-6245f63792ae.jar:?]
mc_1  |         at org.iq80.leveldb.impl.Iq80DBFactory.open(Iq80DBFactory.java:83) ~[90026451-88ee-4ee5-a48c-6245f63792ae.jar:?]
mc_1  |         at xyz.nikitacartes.easyauth.storage.database.LevelDB.initialize(LevelDB.java:29) ~[easyauth-mc1.17.1-1.9.3.jar:?]
mc_1  |         at xyz.nikitacartes.easyauth.storage.DBHelper.openConnection(DBHelper.java:20) ~[easyauth-mc1.17.1-1.9.3.jar:?]
mc_1  |         at xyz.nikitacartes.easyauth.EasyAuth.init(EasyAuth.java:81) ~[easyauth-mc1.17.1-1.9.3.jar:?]
mc_1  |         at xyz.nikitacartes.easyauth.EasyAuth.onInitialize(EasyAuth.java:108) ~[easyauth-mc1.17.1-1.9.3.jar:?]
mc_1  |         at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer$$Lambda$2793/0x0000000039c40088.accept(Unknown Source) ~[?:?]
mc_1  |         at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-1.17.1.jar:?]
mc_1  |         ... 17 more**
mc_1  | 2021-07-26T13:55:00.762Z        INFO    mc-server-runner        Done
```
**Expected behavior**

**Additional context**
Running in the itzg minecraft docker image

These are the mods loaded on startup:
```
[13:54:51] [main/INFO]: [FabricLoader] Loading 64 mods:
mc_1  |         - at_favre_lib_bcrypt@0.9.0
mc_1  |         - at_favre_lib_bytes@1.3.0
mc_1  |         - carpet@1.4.44
mc_1  |         - de_mkammerer_argon2-jvm@2.7
mc_1  |         - easyauth@1.9.3
mc_1  |         - fabric@0.37.1+1.17
mc_1  |         - fabric-api-base@0.3.0+a02b446318
mc_1  |         - fabric-api-lookup-api-v1@1.2.0+2b5c62d018
mc_1  |         - fabric-biome-api-v1@3.1.11+c345aea818
mc_1  |         - fabric-blockrenderlayer-v1@1.1.5+a02b446318
mc_1  |         - fabric-command-api-v1@1.1.3+5ab9934c18
mc_1  |         - fabric-commands-v0@0.2.2+92519afa18
mc_1  |         - fabric-containers-v0@0.1.12+a02b446318
mc_1  |         - fabric-content-registries-v0@0.2.2+a02b446318
mc_1  |         - fabric-crash-report-info-v1@0.1.5+be9da31018
mc_1  |         - fabric-dimensions-v1@2.0.11+6cefd57718
mc_1  |         - fabric-entity-events-v1@1.1.0+a02b446318
mc_1  |         - fabric-events-interaction-v0@0.4.9+a722d8c018
mc_1  |         - fabric-events-lifecycle-v0@0.2.1+92519afa18
mc_1  |         - fabric-game-rule-api-v1@1.0.7+6cefd57718
mc_1  |         - fabric-item-api-v1@1.2.4+a02b446318
mc_1  |         - fabric-item-groups-v0@0.2.10+b7ab612118
mc_1  |         - fabric-key-binding-api-v1@1.0.4+a02b446318
mc_1  |         - fabric-keybindings-v0@0.2.2+36b77c3e18
mc_1  |         - fabric-lifecycle-events-v1@1.4.4+a02b446318
mc_1  |         - fabric-loot-tables-v1@1.0.4+a02b446318
mc_1  |         - fabric-mining-levels-v0@0.1.3+92519afa18
mc_1  |         - fabric-models-v0@0.3.0+a02b446318
mc_1  |         - fabric-networking-api-v1@1.0.12+6cefd57718
mc_1  |         - fabric-networking-blockentity-v0@0.2.11+a02b446318
mc_1  |         - fabric-networking-v0@0.3.2+92519afa18
mc_1  |         - fabric-object-builder-api-v1@1.10.9+b7ab612118
mc_1  |         - fabric-object-builders-v0@0.7.3+a02b446318
mc_1  |         - fabric-particles-v1@0.2.4+a02b446318
mc_1  |         - fabric-registry-sync-v0@0.7.10+e2961fee18
mc_1  |         - fabric-renderer-api-v1@0.4.4+5f02c96918
mc_1  |         - fabric-renderer-indigo@0.4.8+a02b446318
mc_1  |         - fabric-renderer-registries-v1@3.2.0+a02b446318
mc_1  |         - fabric-rendering-data-attachment-v1@0.1.5+a02b446318
mc_1  |         - fabric-rendering-fluids-v1@0.1.13+a02b446318
mc_1  |         - fabric-rendering-v0@1.1.2+92519afa18
mc_1  |         - fabric-rendering-v1@1.6.0+a02b446318
mc_1  |         - fabric-resource-loader-v0@0.4.8+a00e834b18
mc_1  |         - fabric-screen-api-v1@1.0.4+155f865c18
mc_1  |         - fabric-screen-handler-api-v1@1.1.8+a02b446318
mc_1  |         - fabric-structure-api-v1@1.1.13+5ab9934c18
mc_1  |         - fabric-tag-extensions-v0@1.1.4+a02b446318
mc_1  |         - fabric-textures-v0@1.0.6+a02b446318
mc_1  |         - fabric-tool-attribute-api-v1@1.2.12+b7ab612118
mc_1  |         - fabric-transfer-api-v1@1.0.0+3fe3c3f518
mc_1  |         - fabricloader@0.11.6
mc_1  |         - java@16
mc_1  |         - litematica@0.0.0-dev.20210713.103711
mc_1  |         - lithium@0.7.3
mc_1  |         - malilib@0.10.0-dev.24
mc_1  |         - minecraft@1.17.1
mc_1  |         - minihud@0.19.0-dev.20210707.150016
mc_1  |         - net_java_dev_jna_jna@5.5.0
mc_1  |         - org_iq80_leveldb_leveldb@0.12
mc_1  |         - org_iq80_leveldb_leveldb-api@0.12
mc_1  |         - org_mongodb_mongodb-driver-sync@4.1.0
mc_1  |         - packet_tweaker@0.2.0-1.17-pre1
mc_1  |         - server_translations_api@1.4.5+1.17
mc_1  |         - starlight@1.0.0-RC3+fabric.2b7d7ae
```

**Comment by sdas-tech** [comment]
Can confirm that an empty levelDBStore folder gets created:

F:\mcServer\server\mods\EasyAuth
λ ls -la
total 8
drwxr-xr-x 1 surya 197609    0 Jul 27 00:03 .
drwxr-xr-x 1 surya 197609    0 Jul 26 23:55 ..
-rw-r--r-- 1 surya 197609 1797 Jul 27 00:04 config.json
drwxr-xr-x 1 surya 197609    0 Jul 26 23:55 leveldbStore

**Comment by NikitaCartes** [comment]
I don't have much experience with docker, so I try to recreate this way:
1) Install Docker
2) `docker pull itzg/minecraft-server`
3) `mkdir /home/ubuntu/servers/data/`
4) copy into `/data/mods/` `EasyAuth` and `Fabric Api` 
5) 
```
docker run -d -v /home/ubuntu/servers/data/:/data \
    -e TYPE=FABRIC \
    -p 25565:25565 -e EULA=TRUE --name mc itzg/minecraft-server
```
After that I gotted working server:
```
[14:35:42] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/data/fabric-server-1.17.1.jar Service=Knot/Fabric Env=SERVER
[14:35:42] [main/INFO]: Compatibility level set to JAVA_16
[14:35:42] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[14:35:47] [main/INFO]: [EasyAuth] EasyAuth mod by samo_lego, NikitaCartes.
[14:35:47] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zzm000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[14:35:48] [main/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 1.718 ms
[14:35:48] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:35:49] [main/INFO]: Found new data pack Fabric Mods, loading it automatically
[14:35:49] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:35:49] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:35:49] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:35:49] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:35:49] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:35:49] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Easy Authentication Mod, Server Translations API, Fabric Tool Attribute API (v1))
```


As I mentioned I don't have much experience with Docker. Maybe you have something wrong with permission on /data?
Btw, `litematica` and `minihud` is a client-side mods.

**Comment by sdas-tech** [comment]
Sorry for no response.
I tried it on a clean new server (ARM based linux on Oracle cloud) and am getting a similar error:

```
[opc@minecraft-server mcserver]$ docker run -v /home/opc/mcserver/data:/data     -e TYPE=FABRIC     -p 25565:25565 -e EULA=TRUE
--name mc itzg/minecraft-server:java17
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x. 4 1000 1000 93 Nov  2 06:00 /data'
[init] Resolved version given LATEST into 1.17.1
[init] Resolving type given FABRIC
[init] Checking Fabric version information.
[init] Checking Fabric Loader version information.
[init] Downloading https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.9.0/fabric-installer-0.9.0.jar ...
[init] Installing Fabric 1.17.1 using fabric-installer-0.9.0.jar with loader version 0.12.5
Loading Fabric Installer: 0.9.0
Installing Fabric Loader 0.12.5(1.17.1) on the server
Downloading required files
Downloading library net.fabricmc:tiny-mappings-parser:0.3.0+build.17
Downloading library net.fabricmc:sponge-mixin:0.10.6+mixin.0.8.4
Downloading library net.fabricmc:tiny-remapper:0.6.0
Downloading library net.fabricmc:access-widener:2.0.1
Downloading library org.ow2.asm:asm:9.2
Downloading library org.ow2.asm:asm-analysis:9.2
Downloading library org.ow2.asm:asm-commons:9.2
Downloading library org.ow2.asm:asm-tree:9.2
Downloading library org.ow2.asm:asm-util:9.2
Downloading library net.fabricmc:intermediary:1.17.1
Downloading library net.fabricmc:fabric-loader:0.12.5
Generating server launch JAR
Generating server launch JAR: tiny-mappings-parser-0.3.0+build.17.jar
Generating server launch JAR: sponge-mixin-0.10.6+mixin.0.8.4.jar
Generating server launch JAR: tiny-remapper-0.6.0.jar
Generating server launch JAR: access-widener-2.0.1.jar
Generating server launch JAR: asm-9.2.jar
Generating server launch JAR: asm-analysis-9.2.jar
duplicate file: module-info.class
Generating server launch JAR: asm-commons-9.2.jar
duplicate file: module-info.class
Generating server launch JAR: asm-tree-9.2.jar
duplicate file: module-info.class
Generating server launch JAR: asm-util-9.2.jar
duplicate file: module-info.class
Generating server launch JAR: intermediary-1.17.1.jar
Generating server launch JAR: fabric-loader-0.12.5.jar
Downloading Minecraft server
Done
Done, start server by running fabric-server-launch.jar
[init] Creating server.properties in /data/server.properties
[init] Disabling whitelist
[init] Setting whitelist to 'false' in /data/server.properties
[init] Setting white-list to 'false' in /data/server.properties
[init] Adding server-name with 'Dedicated Server' in /data/server.properties
[init] Setting server-port to '25565' in /data/server.properties
[init] Setting motd to 'A Fabric Minecraft Server powered by Docker' in /data/server.properties
[init] Setting enable-rcon to 'true' in /data/server.properties
[init] Setting rcon.password to 'minecraft' in /data/server.properties
[init] Setting rcon.port to '25575' in /data/server.properties
[init] Setting level-name to 'world' in /data/server.properties
[init] Setting online-mode to 'true' in /data/server.properties
[init] Checking for JSON files.
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
[11:14:06] [INFO] [FabricLoader/GameProvider]: Loading for game Minecraft 1.17.1
[11:14:06] [INFO] [FabricLoader/GameRemap]: Fabric is preparing JARs on first launch, this may take a few seconds...
[11:14:14] [main/INFO]: Loading for game Minecraft 1.17.1
[11:14:14] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[11:14:14] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
         - You should install any version of fabric-textures-v0 for the optimal experience.
[11:14:14] [main/INFO]: Loading 47 mods:
        - at_favre_lib_bcrypt 0.9.0
        - at_favre_lib_bytes 1.3.0
        - de_mkammerer_argon2-jvm 2.7
        - easyauth 1.9.7
        - fabric 0.41.3+1.17
        - fabric-api-base 0.3.0+a02b446318
        - fabric-api-lookup-api-v1 1.3.0+cbda931818
        - fabric-biome-api-v1 3.2.1+ffbe6d8f18
        - fabric-command-api-v1 1.1.3+5ab9934c18
        - fabric-commands-v0 0.2.2+92519afa18
        - fabric-containers-v0 0.1.12+cbda931818
        - fabric-content-registries-v0 0.3.0+cbda931818
        - fabric-crash-report-info-v1 0.1.5+be9da31018
        - fabric-dimensions-v1 2.0.12+ffbe6d8f18
        - fabric-entity-events-v1 1.3.0+57bef5a318
        - fabric-events-interaction-v0 0.4.10+fc40aa9d18
        - fabric-events-lifecycle-v0 0.2.1+92519afa18
        - fabric-game-rule-api-v1 1.0.7+cbda931818
        - fabric-item-api-v1 1.2.4+cbda931818
        - fabric-item-groups-v0 0.3.0+ef17126d18
        - fabric-lifecycle-events-v1 1.4.4+a02b446318
        - fabric-loot-tables-v1 1.0.4+a02b446318
        - fabric-mining-levels-v0 0.1.3+92519afa18
        - fabric-networking-api-v1 1.0.13+cbda931818
        - fabric-networking-blockentity-v0 0.2.11+a02b446318
        - fabric-networking-v0 0.3.2+92519afa18
        - fabric-object-builder-api-v1 1.10.9+cbda931818
        - fabric-object-builders-v0 0.7.3+a02b446318
        - fabric-particles-v1 0.2.4+a02b446318
        - fabric-registry-sync-v0 0.7.12+81e15a8918
        - fabric-rendering-data-attachment-v1 0.1.5+a02b446318
        - fabric-rendering-fluids-v1 0.1.14+4658223018
        - fabric-resource-loader-v0 0.4.8+a00e834b18
        - fabric-screen-handler-api-v1 1.1.8+cbda931818
        - fabric-structure-api-v1 1.1.13+5ab9934c18
        - fabric-tag-extensions-v0 1.2.1+81e15a8918
        - fabric-tool-attribute-api-v1 1.2.12+b7ab612118
        - fabric-transfer-api-v1 1.4.1+ffbe6d8f18
        - fabricloader 0.12.5
        - java 17
        - minecraft 1.17.1
        - net_java_dev_jna_jna 5.5.0
        - org_iq80_leveldb_leveldb 0.12
        - org_iq80_leveldb_leveldb-api 0.12
        - org_mongodb_mongodb-driver-sync 4.1.0
        - packet_tweaker 0.2.0-1.17-pre1
        - server_translations_api 1.4.5+1.17
[11:14:14] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/data/fabric-server-1.17.1.jar Service=Knot/Fabric Env=SERVER
[11:14:15] [main/INFO]: Compatibility level set to JAVA_16
[11:14:15] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[11:14:15] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[11:14:18] [main/INFO]: [EasyAuth] EasyAuth mod by samo_lego, NikitaCartes.
[11:14:18] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zch000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[11:14:19] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'easyauth'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-server-1.17.1.jar:?]
        at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) [fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-server-1.17.1.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72) [fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98) [fabric-server-1.17.1.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60) [fabric-server-1.17.1.jar:?]
Caused by: java.lang.RuntimeException: [EasyAuth] Error creating directory!
        at xyz.nikitacartes.easyauth.EasyAuth.init(EasyAuth.java:77) ~[easyauth-mc1.17.1-1.9.7.jar:?]
        at xyz.nikitacartes.easyauth.EasyAuth.onInitialize(EasyAuth.java:108) ~[easyauth-mc1.17.1-1.9.7.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-1.17.1.jar:?]
        ... 17 more
2021-11-11T11:14:19.586Z        INFO    mc-server-runner        Done
```


Heres the permissions on /data:

`drwxrwxr-x. 7 opc opc 4096 Nov 11 11:14 data`

definitely looks a permission related issue I think

**Comment by sdas-tech** [comment]
What are the permissions on your /data and /data/mods folders? Are you running docker as root? I think there might be some discrepancy there 

Also I'm not too sure how to get the full stack trace of the error, is there anything I need to do to stop it being truncated with the " ... 17 more" bit?

**Comment by NikitaCartes** [comment]
@sdas-tech btw I replied to you at Discord server

**Comment by NikitaCartes** [comment]
Should be solved as mentioned in №29

**Comment by sdas-tech** [comment]
Can confirm that this is fixed now cheers!
