### ISSUE TITLE
[BUG] Connection to server fails

### ISSUE THREAD

**Issue by anatolykopyl** [NikitaCartes/EasyAuth#75]
**Versions**
* EasyAuth 1.19.3-3.0.0-11
* Fabric API 0.69
* OpenJDK 17.0.5 2022-10-18 LTS

Players can't connect to the server. The logs display the following message:
```
[10:10:07] [Server thread/WARN]: Failed to handle packet for /192.168.1.1:64776
java.lang.NullPointerException: Cannot invoke "java.util.regex.Pattern.matcher(java.lang.CharSequence)" because "xyz.nikitacartes.easyauth.event.AuthEventHandler.usernamePattern" is null
        at xyz.nikitacartes.easyauth.event.AuthEventHandler.checkCanPlayerJoinServer(AuthEventHandler.java:47) ~[easyauth-mc1.19.3-3.0.0-11.jar:?]
        at net.minecraft.class_3324.handler$zbf000$checkCanJoin(class_3324.java:2017) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14586(class_3324.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:102) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.redirect$zfg000$handlePlayerJoin(class_3248.java:1063) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by anatolykopyl** [comment]
Server restart seemingly fixed the issue, probably a one time thing with the configs not generated or something.
