### ISSUE TITLE
[BUG] Cannot init SQL table white using MySQL

### ISSUE THREAD

**Issue by MisaLiu** [NikitaCartes/EasyAuth#82]
**Versions**
* EasyAuth 3.0.0-11
* Fabric API 0.73.0

**Describe the bug**
Plugin cannot init SQL table white using MySQL, the SQL server works fine.

**To Reproduce**
1. Set config file like this:
    ```json
    // ...
    "databaseType": "mysql",
    "MySQLHost": "127.0.0.1",
    "MySQLUser": "mc_server",
    "MySQLPassword": "mc_server",
    "MySQLDatabase": "mc_server",
    "MySQLTableName": "easyauth",
    // ...
    ```
2. Start the server
3. The plugin reports an error and refused to start.

**Expected behavior**
The plugin should works fine.

**Additional context**
This is the error log:

```
[Server] [23:32:21] [main/ERROR]: onInitialize error: 
[Server] xyz.nikitacartes.easyauth.storage.database.DBApiException: [EasyAuth] Failed setting up mysql DB
[Server]        at xyz.nikitacartes.easyauth.storage.database.MySQL.connect(MySQL.java:53) ~[easyauth-mc1.19.3-3.0.0-11.jar:?]
[Server]        at xyz.nikitacartes.easyauth.EasyAuth.onInitialize(EasyAuth.java:109) ~[easyauth-mc1.19.3-3.0.0-11.jar:?]
[Server]        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.13.jar:?]
[Server]        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.13.jar:?]
[Server]        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.13.jar:?]
[Server]        at net.minecraft.server.Main.main(Main.java:102) ~[server-intermediary.jar:?]
[Server]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.13.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.13.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.13.jar:?]
[Server]        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.19.3-loader.0.14.13-launcher.0.11.1.jar:0.11.1]
[Server] Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON NOT NULL,
[Server]     PRIMARY KEY (`id`), UNIQUE (`uuid`)
[Server] ) ENGINE = InnoDB' at line 4
[Server]        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql_mysql-connector-java-8.0.29-d2d514767c6c9651.jar:?]
[Server]        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql_mysql-connector-java-8.0.29-d2d514767c6c9651.jar:?]
[Server]        at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1335) ~[mysql_mysql-connector-java-8.0.29-d2d514767c6c9651.jar:?]
[Server]        at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2085) ~[mysql_mysql-connector-java-8.0.29-d2d514767c6c9651.jar:?]
[Server]        at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1246) ~[mysql_mysql-connector-java-8.0.29-d2d514767c6c9651.jar:?]
[Server]        at xyz.nikitacartes.easyauth.storage.database.MySQL.connect(MySQL.java:38) ~[easyauth-mc1.19.3-3.0.0-11.jar:?]
[Server]        ... 10 more
```

MySQL version: 5.5

**Comment by MRNOBODY-ZST** [comment]
Have you already checked your passwd and whether you have already created a table called "easyauth"? Try use the root account of mysql is also a possible way to solve your problem.

**Comment by MisaLiu** [comment]
> Have you already checked your passwd and whether you have already created a table called "easyauth"? Try use the root account of mysql is also a possible way to solve your problem.

I can connect to the database with the username and password, and i'm sure there's no other table named easyauth.

i'll try the root account later.

**Comment by NikitaCartes** [comment]
Current MySql drivers support only 5.7, and 8.x versions of MySql
