### ISSUE TITLE
[BUG] Invalid player data

### ISSUE THREAD

**Issue by Lordofdryads** [NikitaCartes/EasyAuth#85]
**Versions**
* EasyAuth 1.19.1-3.0.0-15
* Fabric API 0.67.11.19.2
* Minecraft version is 1.19.2

**Describe the bug**
The player tries to join the server but fails, getting an "Invalid player data" error. However, other players can join the server without error.

**To Reproduce**
1. Try to join the server.
2.  Get an "Invalid player data" error.

**Expected behavior**
Don't get an "Invalid player data" error.

**Additional context**
There are many mods on the server including CC: Restitched but I can't remove it as it fixes another mods bug. The server is in offline mode, if that matters.

The error when player join server:

[13:04:01] [Server thread/ERROR]: Error while reading power holder data: Cannot read field "password" because "cache" is null
[13:04:01] [Server thread/ERROR]: Couldn't place player in world
net.minecraft.class_148: Loading entity NBT
        at net.minecraft.class_1297.method_5651(class_1297.java:1815) ~[server-intermediary.jar:?]
        at net.minecraft.class_29.method_261(class_29.java:56) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14600(class_3324.java:360) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:151) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_33800(class_3248.java:151) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:138) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.redirect$bfg000$handlePlayerJoin(class_3248.java:1063) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_18784(class_3248.java:73) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot read field "password" because "cache" is null
        at net.minecraft.class_3222.getAuthMessage(class_3222.java:6353) ~[server-intermediary.jar:?]
        at xyz.nikitacartes.easyauth.event.AuthEventHandler.onPlayerCommand(AuthEventHandler.java:167) ~[easyauth-mc1.19.1-3.0.0-15.jar:?]
        at net.minecraft.class_2170.handler$zph000$checkCanUseCommands(class_2170.java:1017) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.method_9249(class_2170.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.method_44252(class_2170.java:264) ~[server-intermediary.jar:?]
        at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$15(EntityActions.java:235) ~[apoli-2.6.1-b666438ef8105be6.jar:?]
        at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41) ~[apoli-2.6.1-b666438ef8105be6.jar:?]
        at io.github.apace100.apoli.power.ActionOnCallbackPower.onAdded(ActionOnCallbackPower.java:61) ~[apoli-2.6.1-b666438ef8105be6.jar:?]
        at io.github.apace100.apoli.component.PowerHolderComponentImpl.addPower(PowerHolderComponentImpl.java:162) ~[apoli-2.6.1-b666438ef8105be6.jar:?]
        at io.github.apace100.origins.component.PlayerOriginComponent.grantPowersFromOrigin(PlayerOriginComponent.java:88) ~[1.19.1-2-Origins-1.7.1.jar:?]
        at io.github.apace100.origins.component.PlayerOriginComponent.readFromNbt(PlayerOriginComponent.java:156) ~[1.19.1-2-Origins-1.7.1.jar:?]
        at dev.onyxstudios.cca.internal.base.AbstractComponentContainer.fromTag(AbstractComponentContainer.java:97) ~[cardinal-components-base-5.0.1-be3965b8c09b15dd.jar:?]
        at net.minecraft.class_1297.handler$zhm000$fromTag(class_1297.java:8126) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5651(class_1297.java:1806) ~[server-intermediary.jar:?]
        ... 15 more
[13:04:01] [Server thread/INFO]: com.mojang.authlib.GameProfile@c4d24a7[id=ea39309e-6968-3749-b0ff-d7b926191ecd,name=rae,properties={textures=[com.mojang.authlib.properties.Property@6c5b360d]},legacy=false] (/109.86.148.123:50105) lost connection: Invalid player data
[13:04:01] [Server thread/WARN]: handleDisconnection() called twice

**Comment by NikitaCartes** [comment]
It should be fixed with 3.0.0-14 update
