### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by berkaykeremoltuluoglu** [NikitaCartes/EasyAuth#93]
**Versions**
* EasyAuth-mc1.19.3-3.0.0-14
* Fabric API -0.76.1+1.19.3
**Describe the bug**
I keep getting this error since i downloaded this mod on my server

**To Reproduce**

**Expected behavior**

**Additional context**
Internal Excepiton: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index 23 out of bounds for length 5

[15:29:59] [Server thread/WARN]: Failed to handle packet for /********
java.lang.NullPointerException: Cannot invoke "java.util.regex.Pattern.matcher(j
ava.lang.CharSequence)" because "xyz.nikitacartes.easyauth.event.AuthEventHandle
r.usernamePattern" is null
        at xyz.nikitacartes.easyauth.event.AuthEventHandler.checkCanPlayerJoinSe
rver(AuthEventHandler.java:48) ~[easyauth-mc1.19.3-3.0.0-14.jar:?]
        at net.minecraft.class_3324.handler$zzf000$easyauth$checkCanJoin(class_3
324.java:1017) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14586(class_3324.java) ~[server-inter
mediary.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:102) ~[server-i
ntermediary.jar:?]
        at net.minecraft.class_3248.redirect$zeg000$fabric-networking-api-v1$han
dlePlayerJoin(class_3248.java:1063) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[server-in
termediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-i
ntermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-i
ntermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java
:897) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-in
termediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java
:830) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.jav
a:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.jav
a:264) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[15:29:59] [Server thread/INFO]: com.mojang.authlib.GameProfile@2a0b85b1[id=*********,name=*********,properties={},legacy=false] (/5.
25.20.16:40559) lost connection: Internal server error
[15:37:23] [Server thread/INFO]: /*********lost connection: Internal
 Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsE
xception: readerIndex(11) + length(1) exceeds writerIndex(11): PooledUnsafeDirec
tByteBuf(ridx: 11, widx: 11, cap: 11)
S

**Comment by NikitaCartes** [comment]
Try with that release: https://github.com/NikitaCartes/EasyAuth/releases/tag/3.0.0-15
