### ISSUE TITLE
[BUG] Unable to start server after adding EasyAuth

### ISSUE THREAD

**Issue by Chun-QiuCC** [NikitaCartes/EasyAuth#97]
**Versions**
* easyauth-mc1.20-3.0.0-17
* fabric-api-0.83.0+1.20

**Describe the bug**
Unable to start Minecraft server after adding EasyAuth

**To Reproduce**
1. add easyauth
2. start minecraft server
3. error

**Expected behavior**
Start the server normally

**Additional context**
```
[Server] [02:42:16] [main/ERROR]: Failed to start the minecraft server
[Server] java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'easyauth'!
[Server]  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
[Server]  at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
[Server]  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
[Server]  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
[Server]  at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
[Server]  at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
[Server]  at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
[Server]  at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
[Server]  at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
[Server]  at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
[Server] Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.util.Properties.getProperty(String)" is null
[Server]  at xyz.nikitacartes.easyauth.EasyAuth.init(EasyAuth.java:67) ~[%5Blogin%5Deasyauth-mc1.20-3.0.0-17.jar:?]
[Server]  at xyz.nikitacartes.easyauth.EasyAuth.onInitialize(EasyAuth.java:107) ~[%5Blogin%5Deasyauth-mc1.20-3.0.0-17.jar:?]
[Server]  at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
[Server]  ... 7 more
```

**Comment by NikitaCartes** [comment]
Hmm. Your server.properties is lack of `enforce-secure-profile` somehow.

**Comment by Chun-QiuCC** [comment]
> Hmm. Your server.properties is lack of `enforce-secure-profile` somehow.

我直接从1.18.2移植了server.properties文件，请问我应该重新生成它吗？

**Comment by NikitaCartes** [comment]
You can download fixed version from here: https://github.com/NikitaCartes/EasyAuth/actions/runs/5326332448

**Comment by Chun-QiuCC** [comment]
> Hmm. Your server.properties is lack of `enforce-secure-profile` somehow.

I directly ported the server.properties file from 1.18.2. Should I regenerate it?

**Comment by NikitaCartes** [comment]
Nah, I fixed it. Minecraft probably will add that setting by itself after normal start.

**Comment by Chun-QiuCC** [comment]
> Nah, I fixed it. Minecraft probably will add that setting by itself after normal start.

Thank you very much!
